// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ChineseZodiac
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("zodiacYear")]
        public long ZodiacYear { get; set; }

        [JsonProperty("animal")]
        public string Animal { get; set; }

        [JsonProperty("animalChinese")]
        public string AnimalChinese { get; set; }

        [JsonProperty("element")]
        public string Element { get; set; }

        [JsonProperty("elementChinese")]
        public string ElementChinese { get; set; }

        [JsonProperty("elementColor")]
        public string ElementColor { get; set; }

        [JsonProperty("polarity")]
        public string Polarity { get; set; }

        [JsonProperty("traits")]
        public string[] Traits { get; set; }

        [JsonProperty("sexagenaryCyclePosition")]
        public long SexagenaryCyclePosition { get; set; }

        [JsonProperty("fullName")]
        public string FullName { get; set; }

        [JsonProperty("chineseNewYear")]
        public DateTimeOffset ChineseNewYear { get; set; }
    }
}
